workflows:
  ios-unsigned:
    name: iOS Unsigned IPA
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build unsigned IPA
        script: |
          flutter build ipa --release --no-codesign --export-options-plist=ios/exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
